# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readbed <- function(bedfile, N, p, myrows, mycols, verbose = TRUE) {
    .Call(`_mar_readbed`, bedfile, N, p, myrows, mycols, verbose)
}

sfsloopC <- function(X) {
    .Call(`_mar_sfsloopC`, X)
}

sfsmatC <- function(X) {
    .Call(`_mar_sfsmatC`, X)
}

sfsC <- function(X, myrows, mycols) {
    .Call(`_mar_sfsC`, X, myrows, mycols)
}

Hn <- function(N) {
    .Call(`_mar_Hn`, N)
}

rcpparma_hello_world <- function() {
    .Call(`_mar_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mar_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mar_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mar_rcpparma_bothproducts`, x)
}

